### ISSUE TITLE
make minicluster - Syntax error in python scripts

### ISSUE THREAD

**Issue by oilandcode** [uber/peloton#7]
$PELOTON=app make minicluster
PELOTON=app ./scripts/minicluster.sh setup
Using base prefix '/anaconda3'
New python executable in /Users//go/src/github.com/uber/peloton/env/bin/python
Installing setuptools, pip, wheel...
done.
Traceback (most recent call last):
  File "tools/minicluster/main.py", line 22, in <module>
    import minicluster
  File "/Users//go/src/github.com/uber/peloton/tools/minicluster/minicluster.py", line 8, in <module>
    import print_utils
  File "/Users//go/src/github.com/uber/peloton/tools/minicluster/print_utils.py", line 13
    print bcolors.OKBLUE + message + bcolors.ENDC
                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(bcolors.OKBLUE + message + bcolors.ENDC)?
make: *** [minicluster] Error 1

**Comment by mabansal** [comment]
Is this issue still exists?

**Comment by talaniz** [comment]
@mabansal I have run this recently and no longer see the syntax error.

**Comment by talaniz** [comment]
@oilandcode would you mind doing a pull and checking this? There has been some work to address this, but would like to get some user confirmation.
